env:
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@master
    - continue-on-error: true
      name: Use Nodejs ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - continue-on-error: true
      env:
        GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      name: Deploy
      run: npm install && npm run deploy
    strategy:
      matrix:
        node-version:
        - 16.x
name: CI
on:
  repository_dispatch:
    types: trigger-ga___deploy.yml
